name: Elasticsearch CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project with Maven
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  artifact:
    runs-on: ubuntu-latest
    name: Build Docker image
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the image in Maven
        run: docker build -t netcracker/elasticsearch-service .

  deploy:
    runs-on: ubuntu-latest
    name: Publish Docker image to Github Packages
    needs: [build, artifact]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish the image
        run: docker push docker.pkg.github.com/NetcrackerEducationCenter/elasticsearch/netcracker/elasticsearch-service:latest