name: Elasticsearch CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project with Maven
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  artifact:
    runs-on: ubuntu-latest
    name: Publish to Github Packages
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    runs-on: ubuntu-latest
    name: Build the Docker image
    needs: [build, artifact]
    steps:
     - name: Execure build script
       with:
        script: |
         docker build -t netcracker/education-center-elasticsearch:1.0
         docker push netcracker/education-center-elasticsearch:1.0
