name: Push to main branch workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifact:
    runs-on: ubuntu-latest
    name: Publish to Github Packages
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}